<?php require('template/header.phtml') ?>
<header class="masthead text-center text-white d-flex" style="background-image:url('/assets/img/header.jpg');">
    <div class="container my-auto">
        <div class="row">
            <div class="col-lg-10 mx-auto">
                <h2 class="text-uppercase"><strong>Apply for a project application!</strong></h2>
                <hr>
            </div>
        </div>
        <div class="col-lg-8 mx-auto">
            <p class="text-faded mb-5">Create an account or login to keep track of your project application!</p><a class="btn btn-primary btn-xl js-scroll-trigger" role="button" href="#services">Find Out More</a>
        </div>
    </div>
</header>
<section id="about" class="bg-primary">
    <div class="container">
        <div class="row">
            <div class="col offset-lg-8 mx-auto text-center">
                <h2 class="text-white section-heading">Want To Upload Your Project Application?</h2>
                <hr class="light my-4">
                <p class="text-faded mb-4">You can start your very own project today. All you need to do is submit an application here! Create an account or login to keep track of your project application!</p><a class="btn btn-light btn-xl js-scroll-trigger" role="button" href="#services">Get Started!</a>
            </div>
        </div>
    </div>
</section>
<section id="services">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="section-heading">At Your Service</h2>
                <hr class="my-4">
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-lg-3 text-center">
                <div class="mx-auto service-box mt-5"><i class="fa fa-diamond fa-4x text-primary mb-3 sr-icons" data-aos="zoom-in" data-aos-duration="200" data-aos-once="true"></i>
                    <h3 class="mb-3">Projects</h3>
                    <p class="text-muted mb-0">Project Applications are uploaded daily on to our website.</p>
                </div>
            </div>
            <div class="col-md-6 col-lg-3 text-center">
                <div class="mx-auto service-box mt-5"><i class="fa fa-paper-plane fa-4x text-primary mb-3 sr-icons" data-aos="zoom-in" data-aos-duration="200" data-aos-delay="200" data-aos-once="true"></i>
                    <h3 class="mb-3">Ready to Ship</h3>
                    <p class="text-muted mb-0">There are many experienced developers to deliver your project! </p>
                </div>
            </div>
            <div class="col-md-6 col-lg-3 text-center">
                <div class="mx-auto service-box mt-5"><i class="fa fa-newspaper-o fa-4x text-primary mb-3 sr-icons" data-aos="zoom-in" data-aos-duration="200" data-aos-delay="400" data-aos-once="true"></i>
                    <h3 class="mb-3">Create an Account</h3>
                    <p class="text-muted mb-0">Keep your project application up to date by creating an account!</p>
                </div>
            </div>
            <div class="col-md-6 col-lg-3 text-center">
                <div class="mx-auto service-box mt-5"><i class="fa fa-heart fa-4x text-primary mb-3 sr-icons" data-aos="fade" data-aos-duration="200" data-aos-delay="600" data-aos-once="true"></i>
                    <h3 class="mb-3">Made with Love</h3>
                    <p class="text-muted mb-0">The project you desire will be made with love!</p>
                </div>
            </div>
        </div>
    </div>
</section>
<section id="portfolio" class="p-0">
    <div class="container-fluid p-0">
        <div class="row no-gutters popup-gallery">
            <div class="col-sm-6 col-lg-4"><a class="portfolio-box" href="/assets/img/fullsize/7.png"><img class="img-fluid" src="assets/img/thumbnails/7.png">
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded"><span>Projects</span></div>
                            <div class="project-name"><span>Design System</span></div>
                        </div>
                    </div>
                </a></div>
            <div class="col-sm-6 col-lg-4"><a class="portfolio-box" href="/assets/img/fullsize/13.png"><img class="img-fluid" src="assets/img/thumbnails/13.png">
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded"><span>Projects</span></div>
                            <div class="project-name"><span>PAM</span></div>
                        </div>
                    </div>
                </a></div>
            <div class="col-sm-6 col-lg-4"><a class="portfolio-box" href="/assets/img/fullsize/14.png"><img class="img-fluid" src="assets/img/thumbnails/14.png">
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded"><span>Project</span></div>
                            <div class="project-name"><span>Tedd</span></div>
                        </div>
                    </div>
                </a></div>
            <div class="col-sm-6 col-lg-4"><a class="portfolio-box" href="/assets/img/fullsize/9.png"><img class="img-fluid" src="assets/img/thumbnails/9.png">
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded"><span>Project</span></div>
                            <div class="project-name"><span>Ensis</span></div>
                        </div>
                    </div>
                </a></div>
            <div class="col-sm-6 col-lg-4"><a class="portfolio-box" href="/assets/img/fullsize/11.png"><img class="img-fluid" src="assets/img/thumbnails/11.png">
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded"><span>Project</span></div>
                            <div class="project-name"><span>Flood Risk</span></div>
                        </div>
                    </div>
                </a></div>
            <div class="col-sm-6 col-lg-4"><a class="portfolio-box" href="/assets/img/fullsize/10.png"><img class="img-fluid" src="assets/img/thumbnails/10.png">
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded"><span>Project</span></div>
                            <div class="project-name"><span>Ensis 2</span></div>
                        </div>
                    </div>
                </a></div>
        </div>
    </div>
</section>
<section class="bg-dark text-white">
    <div class="container text-center">
        <div class="testimonials-clean">
            <div class="container">
                <div class="intro">
                    <h2 class="text-center">Our Team!</h2>
                    <p class="text-center">Know about the team where they work behind the scenes!</p>
                </div>
                <div class="row people">
                    <div class="col-md-6 col-lg-4 item">
                        <div class="box">
                            <p class="description">Aenean tortor est, vulputate quis leo in, vehicula rhoncus lacus. Praesent aliquam in tellus eu gravida. Aliquam varius finibus est.</p>
                        </div>
                        <div class="author"><img class="rounded-circle" src="assets/img/1.jpg">
                            <h5 class="name">example</h5>
                            <p class="title">CEO of KRM Projects</p>
                        </div>
                    </div>
                    <div class="col-md-6 col-lg-4 item">
                        <div class="box">
                            <p class="description">Praesent aliquam in tellus eu gravida. Aliquam varius finibus est, et interdum justo suscipit id.</p>
                        </div>
                        <div class="author"><img class="rounded-circle" src="assets/img/3.jpg">
                            <h5 class="name">Example</h5>
                            <p class="title">Founder of Styles&nbsp;</p>
                        </div>
                    </div>
                    <div class="col-md-6 col-lg-4 item">
                        <div class="box">
                            <p class="description">Aliquam varius finibus est, et interdum justo suscipit. Vulputate quis leo in, vehicula rhoncus lacus. Praesent aliquam in tellus eu.</p>
                        </div>
                        <div class="author"><img class="rounded-circle" src="assets/img/2.jpg">
                            <h5 class="name">Example&nbsp;</h5>
                            <p class="title">Owner of Creative Ltd.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <script src="assets/js/jquery.min.js"></script>
        <script src="assets/bootstrap/js/bootstrap.min.js"></script>
</section>
    <section id="contact">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="text-uppercase section-heading">Contact Us</h2>
                    <h4 class="section-subheading text-muted">If you want to contact us then feel free to do so and we'll message you back in time!</h4>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <form id="contactForm" name="contactForm" novalidate="novalidate">
                        <div class="form-row">
                            <div class="col col-md-6">
                                <div class="form-group"><input class="form-control" type="text" name="name" placeholder="Your Name *" required=""><small class="form-text text-danger flex-grow-1 help-block lead"></small></div>
                                <div class="form-group"><input class="form-control" type="email" name="email" placeholder="Your Email *" required=""><small class="form-text text-danger help-block lead"></small></div>
                                <div class="form-group"><input class="form-control" type="tel" name ="telephone" placeholder="Your Phone *" required=""><small class="form-text text-danger help-block lead"></small></div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group"><textarea style="height: 150px" class="form-control" name="message" placeholder="Your Message *" required=""></textarea><small class="form-text text-danger help-block lead"></small></div>
                            </div>
                            <div class="col">
                                <div class="clearfix"></div>
                            </div>
                            <div class="col-lg-12 text-center">
                                <div id="success"></div><button class="btn btn-primary btn-xl text-uppercase" name="sendMessageButton" type="submit">Send Message</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
<script src="assets/js/jquery.min.js"></script>
<script src="assets/bootstrap/js/bootstrap.min.js"></script>
<script src="assets/js/bs-init.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>
<script src="assets/js/creative.js"></script>
</body>
<?php require('template/footer.phtml') ?>